"""updating the database

Revision ID: 066fcbc5e126
Revises: 9127a00cc858
Create Date: 2021-04-28 19:14:42.827329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '066fcbc5e126'
down_revision = '9127a00cc858'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
