"""updating the users

Revision ID: 5aec378e13df
Revises: 066fcbc5e126
Create Date: 2021-04-28 19:16:34.937732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aec378e13df'
down_revision = '066fcbc5e126'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('category', sa.String(), nullable=False))
    op.drop_column('users', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('posts', 'category')
    # ### end Alembic commands ###
