"""adding the user role

Revision ID: 64f9d1595e22
Revises: 61df710367e8
Create Date: 2021-04-30 21:21:05.587819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64f9d1595e22'
down_revision = '61df710367e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'comment',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index(op.f('ix_pitches_category'), 'pitches', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pitches_category'), table_name='pitches')
    op.alter_column('comments', 'comment',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
